version: "3.8"

services:
  migration:
    image: thewca/wca-live-server
    environment:
      - HOST
      - DATABASE_URL
      - SECRET_KEY_BASE
      - WCA_HOST
      - WCA_OAUTH_CLIENT_ID
      - WCA_OAUTH_CLIENT_SECRET
    command: migrate
  server:
    image: thewca/wca-live-server
    restart: always
    environment:
      - HOST
      - DATABASE_URL
      - SECRET_KEY_BASE
      - WCA_HOST
      - WCA_OAUTH_CLIENT_ID
      - WCA_OAUTH_CLIENT_SECRET
    volumes:
      # Persist cache data (like regional records).
      - server-tmp:/app/tmp
    expose:
      - "4000"
    logging:
      driver: json-file
      options:
        # Note: by default Docker doesn't impose any limits on logs storage.
        max-file: '10'
        max-size: '10m'
  client:
    image: thewca/wca-live-client
    volumes:
      - client:/build
  nginx:
    image: thewca/wca-live-nginx
    restart: always
    environment:
      - HOST
      - REQUEST_SSL_CERT
      - EMAIL
    volumes:
      - client:/webroot
      - letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
      - "443:443"
    logging:
      driver: json-file
      options:
        # Note: by default Docker doesn't impose any limits on logs storage.
        max-file: '10'
        max-size: '10m'

volumes:
  # Client build artifacts.
  client:
  # Letsencrypt data (certificates).
  letsencrypt:
  # Server cache/tmp stuff.
  server-tmp:
